/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ButtonsLayerComponent: typeof import('./src/components/ButtonsLayerComponent.vue')['default']
    FooterComponent: typeof import('./src/components/FooterComponent.vue')['default']
    KeybindComponent: typeof import('./src/components/KeybindComponent.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NCarousel: typeof import('naive-ui')['NCarousel']
    NDivider: typeof import('naive-ui')['NDivider']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NInput: typeof import('naive-ui')['NInput']
    NSelect: typeof import('naive-ui')['NSelect']
    NSlider: typeof import('naive-ui')['NSlider']
    SettingsLayerComponent: typeof import('./src/components/SettingsLayerComponent.vue')['default']
    TextareaLayerComponent: typeof import('./src/components/TextareaLayerComponent.vue')['default']
  }
}
