/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ButtonsLayerComponent: typeof import('./src/components/ButtonsLayerComponent.vue')['default']
    HeaderComponent: typeof import('./src/components/HeaderComponent.vue')['default']
    KeybindComponent: typeof import('./src/components/KeybindComponent.vue')['default']
    SettingsLayerComponent: typeof import('./src/components/SettingsLayerComponent.vue')['default']
    TextAreaLayerComponent: typeof import('./src/components/TextAreaLayerComponent.vue')['default']
  }
}
